# Generated by Django 5.2.5 on 2026-04-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_payment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="country",
            field=models.CharField(default="US", max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="state",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="payment",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
